#!/bin/bash

export PATH=/sbin:/usr/sbin

interface=$1
action=$2

if [ ! -z "$action" -a "$action" != "up" ]; then
    exit 0
fi

script_status=0

set_token() {
    ip token set $1 dev $2
    status=$?
    if [ $script_status -eq 0 ]; then
        script_status=$status
    fi
}

[ "$interface" == "eth0" -o "$interface" == "_all_" ] && set_token ::10 eth0
[ "$interface" == "eth1" -o "$interface" == "_all_" ] && set_token ::12 eth1

exit $script_status
