#!/bin/bash

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

interface=$1
action=$2

[ -z "$action" ] && action="up"

if [ "$interface" == "eth0" -a "$action" == "up" ]; then
    ip token set ::10 dev eth0
fi
